version: '2.1'
services:
    json:
        build: ./app-json
        image: projeto/json
        container_name: json
        depends_on:
            banco:
                condition: service_healthy
        links:
            - "banco:host-banco"             
    web:
        build: .
        image: projeto/web
        container_name: web
        ports:
          - "8081:8080"
        depends_on:
            core:
                condition: service_healthy
        links:
            - "core:host-core"
    core:
        build: ./core
        image: projeto/core
        container_name: core
        ports:
          - "3700:3700"
          - "8082:8080"
        depends_on:
            banco:
                condition: service_healthy
        links:
            - "banco:host-banco"
        healthcheck:
            test: "exit 0"
        volumes:
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
    banco:
        build: ./postgres
        image: projeto/banco
        container_name: banco
        ports:
            - "5433:5432"
        healthcheck:
            test: "exit 0"
